// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qovgcumafbauktwthurx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvdmdjdW1hZmJhdWt0d3RodXJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDkyMTUsImV4cCI6MjA2NDYyNTIxNX0.VXoZJkFyJw2xCtMfHvUQBOHTNAZgPQ2uMTM8bgD-mVo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);